spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/postgres
    password: postgres
    username: postgres
  jpa:
    show-sql: true

  liquibase:
    change-log: classpath:/db/changelog/db.changelog-master.yaml
    enabled: true

server:
  port: 8083